name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build

      - name: Sync to S3
        run: aws s3 sync ./out s3://sagtechfrontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_API_URL: http://127.0.0.1:8000/api/v1/saggroup
          NEXT_PUBLIC_ABSTRACT_API_URL: https://emailvalidation.abstractapi.com/v1/
          ABSTRACT_API_KEY: 615c33ba7e924365a145195c5d92b6bd






